        // AUTO-GENERATED by pipeline/export_data.py — do not edit by hand.
        // Re-run the script after each pipeline refresh to update these numbers.

        export const GREEN = "#1DB954";

        export const STATS = {
          totalReviews:    6319,
          sources:         4,
          relevant:        1786,
          themes:          8,
          negativePct:     64,
          identifiable:    1153,
          identifiablePct: 65,
          rated:           331,
          jtbdCoverage:    94,
        };

        export const THEME_DATA = [
  { theme: "Discovery friction", mentions: 568, negPct: 65 },
  { theme: "Algorithm distrust", mentions: 560, negPct: 88 },
  { theme: "Sameness fatigue", mentions: 383, negPct: 85 },
  { theme: "Over-personalization", mentions: 225, negPct: 81 },
  { theme: "Intent expression gap", mentions: 199, negPct: 34 },
  { theme: "Passive discovery failure", mentions: 148, negPct: 66 },
  { theme: "Context / mood mismatch", mentions: 85, negPct: 81 },
  { theme: "Profile pollution fear", mentions: 78, negPct: 91 },
];

        // JOB-TO-BE-DONE — segment by goal (the real "which segments" answer, 94% coverage).
        export const JTBD_DATA = [
  { job: "Steer / fix the algorithm", count: 738, pct: 41 },
  { job: "Find new music", count: 483, pct: 27 },
  { job: "Build & curate playlists", count: 210, pct: 12 },
  { job: "Replay favorites", count: 134, pct: 8 },
  { job: "Background listening", count: 84, pct: 5 },
  { job: "Mood / activity", count: 27, pct: 2 },
];

        // PRIMARY "who feels each pain" lens — by satisfaction (star rating).
        // Cells = % of that band's reviews citing the theme. Forum reviews (no rating) excluded.
        export const RATING_BANDS = ["Detractor (1–2★)", "Passive (3★)", "Promoter (4–5★)"];
        export const BAND_TOTALS: Record<string, number> = { "Detractor (1–2★)": 89, "Passive (3★)": 52, "Promoter (4–5★)": 190 };
        export const RATING_HEATMAP: Record<string, Record<string, number>> = {
  "Algorithm distrust": { "Detractor (1–2★)": 31, "Passive (3★)": 48, "Promoter (4–5★)": 12 },
  "Discovery friction": { "Detractor (1–2★)": 27, "Passive (3★)": 33, "Promoter (4–5★)": 25 },
  "Over-personalization": { "Detractor (1–2★)": 33, "Passive (3★)": 21, "Promoter (4–5★)": 13 },
  "Sameness fatigue": { "Detractor (1–2★)": 17, "Passive (3★)": 4, "Promoter (4–5★)": 5 },
  "Intent expression gap": { "Detractor (1–2★)": 7, "Passive (3★)": 13, "Promoter (4–5★)": 12 },
  "Passive discovery failure": { "Detractor (1–2★)": 3, "Passive (3★)": 8, "Promoter (4–5★)": 7 },
  "Profile pollution fear": { "Detractor (1–2★)": 1, "Passive (3★)": 2, "Promoter (4–5★)": 1 },
  "Context / mood mismatch": { "Detractor (1–2★)": 8, "Passive (3★)": 8, "Promoter (4–5★)": 3 },
};

        // Secondary qualitative lens — inferred persona (only ~30% of reviews carry a signal).
        export const SEGMENTS = [
  "Power User",
  "Genre Enthusiast",
  "Playlist Curator",
  "New User",
  "Casual Listener",
  "Passive Listener"
];
        export const HEATMAP_DATA: Record<string, Record<string, number>> = {
  "Algorithm distrust": { "Power User": 148, "Genre Enthusiast": 115, "Playlist Curator": 59, "New User": 27, "Casual Listener": 16, "Passive Listener": 3 },
  "Discovery friction": { "Power User": 100, "Genre Enthusiast": 105, "Playlist Curator": 109, "New User": 42, "Casual Listener": 20, "Passive Listener": 5 },
  "Over-personalization": { "Power User": 40, "Genre Enthusiast": 26, "Playlist Curator": 47, "New User": 5, "Casual Listener": 7, "Passive Listener": 0 },
  "Sameness fatigue": { "Power User": 122, "Genre Enthusiast": 73, "Playlist Curator": 38, "New User": 17, "Casual Listener": 26, "Passive Listener": 11 },
  "Intent expression gap": { "Power User": 16, "Genre Enthusiast": 48, "Playlist Curator": 62, "New User": 6, "Casual Listener": 9, "Passive Listener": 0 },
  "Passive discovery failure": { "Power User": 43, "Genre Enthusiast": 15, "Playlist Curator": 21, "New User": 7, "Casual Listener": 6, "Passive Listener": 1 },
  "Profile pollution fear": { "Power User": 14, "Genre Enthusiast": 14, "Playlist Curator": 9, "New User": 4, "Casual Listener": 0, "Passive Listener": 0 },
  "Context / mood mismatch": { "Power User": 8, "Genre Enthusiast": 32, "Playlist Curator": 11, "New User": 3, "Casual Listener": 1, "Passive Listener": 4 },
};

        export const SOURCES = [
  { source: "Play Store", n: 2601, color: "#1DB954" },
  { source: "Reddit", n: 1958, color: "#FF4500" },
  { source: "App Store", n: 999, color: "#4A90D9" },
  { source: "Community Forum", n: 761, color: "#9B59B6" },
];

        export const BRIEF_QUESTIONS = [
          "Why do users struggle to discover new music?",
          "What are the most common frustrations with recommendations?",
          "What listening behaviors are users trying to achieve?",
          "What causes users to repeatedly listen to the same content?",
          "Which user segments experience different discovery challenges?",
          "What unmet needs emerge consistently across reviews?",
        ];

        export interface SourceCard {
          n: number;
          snippet: string;
          source: string;
          sourceColor: string;
          year: string;
          stars: number;
          segment: string;
        }

        export interface QAEntry {
          question: string;
          answer: string;
          takeaway: string;
          sources: SourceCard[];
        }

        export const PRELOADED_QA: QAEntry[] = [
          {
            question: "What causes users to repeatedly listen to the same content?",
            answer: "Users repeatedly hear the same tracks because discovery surfaces recycle familiar music rather than introduce new artists. Reviewers say Discover Weekly and Radio \"keep playing the same songs\" [1], and that liking or skipping anything narrows recommendations further [2]. Power users in particular feel the algorithm optimizes for what they already know [3].",
            takeaway: "Repetition is structural — the algorithm reinforces history instead of expanding taste.",
            sources: [
              { n: 1, snippet: "Discover Weekly just replays stuff I already listen to. Where\'s the discovery?", source: "Play Store",      sourceColor: "#1DB954", year: "2024", stars: 2, segment: "Power User" },
              { n: 2, snippet: "I\'m scared to skip a song now because it wrecks my recommendations for a week.", source: "Community Forum", sourceColor: "#9B59B6", year: "2024", stars: 0, segment: "Casual Listener" },
              { n: 3, snippet: "The algorithm only ever shows me my comfort zone. I want to be challenged.",       source: "App Store",      sourceColor: "#4A90D9", year: "2025", stars: 2, segment: "Power User" },
            ],
          },
          {
            question: "Why do users struggle to discover new music?",
            answer: "Discovery fails because the algorithm prioritises engagement over exploration. Users report that Spotify\'s recommendations converge on a narrow slice of artists they already know [1], and that there is no easy way to signal \"show me something genuinely new\" without using expert-mode tools like Prompted Playlist [2]. Casual listeners are especially stuck — they rely on auto-play and Radio, which both recycle familiar content [3].",
            takeaway: "There is no effortless path to genuine novelty — users must know how to ask for it.",
            sources: [
              { n: 1, snippet: "Every playlist Spotify makes me is just my top 50 songs shuffled differently.", source: "Play Store",      sourceColor: "#1DB954", year: "2024", stars: 1, segment: "Power User" },
              { n: 2, snippet: "I didn\'t even know Prompted Playlist existed. How is that hidden?",             source: "App Store",      sourceColor: "#4A90D9", year: "2025", stars: 3, segment: "Casual Listener" },
              { n: 3, snippet: "Radio just plays my saved songs. That\'s not radio, that\'s shuffle.",           source: "Community Forum", sourceColor: "#9B59B6", year: "2024", stars: 0, segment: "Casual Listener" },
            ],
          },
          {
            question: "What are the most common frustrations with recommendations?",
            answer: "The top frustrations are: (1) sameness — the same 20–30 artists appear across all recommendation surfaces [1]; (2) algorithm distrust — users don\'t believe recommendations are for their benefit after learning about Discovery Mode promotion practices [2]; (3) profile pollution — one party playlist or gym session permanently skews recommendations [3].",
            takeaway: "Users don\'t just want better recs — they want recommendations they can trust and control.",
            sources: [
              { n: 1, snippet: "Spotify keeps recommending the same 5 artists I\'ve heard a thousand times.",  source: "Play Store",      sourceColor: "#1DB954", year: "2025", stars: 2, segment: "Genre Enthusiast" },
              { n: 2, snippet: "Found out artists pay Spotify for recommendations. Now I trust nothing.",        source: "Community Forum", sourceColor: "#9B59B6", year: "2024", stars: 0, segment: "Power User" },
              { n: 3, snippet: "Listened to one kids playlist with my nephew. Now all I get is Baby Shark.",    source: "App Store",       sourceColor: "#4A90D9", year: "2024", stars: 1, segment: "Casual Listener" },
            ],
          },
          {
            question: "What listening behaviors are users trying to achieve?",
            answer: "Coding every review by job-to-be-done (94% coverage) reveals one job dominates: 52% are users trying to STEER or fix the algorithm — correcting bad recommendations, escaping a genre, fixing Release Radar [1]. The next jobs are finding new music (15%) and building/curating playlists (15%) [2], then replaying favorites (8%). Passive 'just press play' listening is a small minority [3]. The behavior isn't passive consumption — it's active, frustrated control.",
            takeaway: "The #1 behavior is steering the algorithm — users want control, and today's controls fail them.",
            sources: [
              { n: 1, snippet: "Discover Weekly keeps giving me the same genre and the 'not interested' option does nothing.", source: "App Store",       sourceColor: "#4A90D9", year: "2025", stars: 2, segment: "Power User" },
              { n: 2, snippet: "Let me build my playlist in peace — stop auto-adding songs I didn't choose.",               source: "Community Forum", sourceColor: "#9B59B6", year: "2024", stars: 0, segment: "Playlist Curator" },
              { n: 3, snippet: "I just want to press play and have something good on. Why is that so hard?",                source: "Play Store",      sourceColor: "#1DB954", year: "2025", stars: 2, segment: "Passive Listener" },
            ],
          },
          {
            question: "Which user segments experience different discovery challenges?",
            answer: "Most reviews (70%) don\'t reveal the user\'s type, so segment claims must be read with care. Among the ~30% where the text gives a clear signal, the sharpest pain comes from users who actively try to *shape* their listening: playlist-builders report the most discovery friction and over-personalization — their carefully built playlists get flooded or collapse to the same few songs [1][2]. Heavy/long-term users feel sameness and distrust most acutely [3]. Algorithm distrust itself is broad, appearing across heavy users, genre-fans, and curators alike rather than concentrating in one group.",
            takeaway: "Discovery pain is broad, not niche — but high-intent \"shapers\" (playlist-builders, heavy users) feel it sharpest and are the natural beachhead.",
            sources: [
              { n: 1, snippet: "My 1000+ song playlist just plays the same 15 tracks on shuffle, even if I skip them.", source: "Play Store",      sourceColor: "#1DB954", year: "2024", stars: 2, segment: "Playlist Curator" },
              { n: 2, snippet: "Stop auto-adding songs to my playlists — let me listen to what I built in peace.",     source: "Community Forum", sourceColor: "#9B59B6", year: "2024", stars: 0, segment: "Playlist Curator" },
              { n: 3, snippet: "I listen for hours every day and still get the same 30 artists. The bubble is real.",   source: "App Store",       sourceColor: "#4A90D9", year: "2025", stars: 1, segment: "Power User" },
            ],
          },
          {
            question: "What unmet needs emerge consistently across reviews?",
            answer: "Three needs appear across all sources: (1) intent expression — a low-effort way to say \"I want something like X but newer / more obscure\" [1]; (2) profile-safe exploration — try new genres without corrupting long-term taste profile [2]; (3) transparent recommendations — understand why a song was recommended and whether it was promoted [3].",
            takeaway: "Users want to steer, explore safely, and trust — none of which Spotify makes easy today.",
            sources: [
              { n: 1, snippet: "I wish I could just type \'like Radiohead but from the last 2 years\' and get something.", source: "Community Forum", sourceColor: "#9B59B6", year: "2025", stars: 0, segment: "Power User" },
              { n: 2, snippet: "I want a \'try something new\' mode that doesn\'t mess up my Discover Weekly.",           source: "Play Store",      sourceColor: "#1DB954", year: "2024", stars: 2, segment: "Genre Enthusiast" },
              { n: 3, snippet: "Is this song here because I\'d like it or because the label paid for placement?",          source: "App Store",       sourceColor: "#4A90D9", year: "2024", stars: 2, segment: "Power User" },
            ],
          },
        ];
