// AUTO-GENERATED by pipeline/theme_details.py — per-theme drill-down data.

export interface ThemeQuote { n: number; snippet: string; source: string; date: string; rating: number | null; segment: string; }

export interface ThemeDetail { key: string; label: string; definition: string; count: number; negPct: number; sources: {source:string;n:number}[]; summary: string; quotes: ThemeQuote[]; }

export const THEME_DETAILS: Record<string, ThemeDetail> = {
  "Algorithm distrust": {
    "key": "algorithm_distrust",
    "label": "Algorithm distrust",
    "definition": "Users don't trust what the algorithm serves — suspecting promotion/payola, unlabeled AI, or a black box they can't see into.",
    "count": 560,
    "negPct": 88,
    "sources": [
      {
        "source": "Reddit",
        "n": 374
      },
      {
        "source": "Community Forum",
        "n": 110
      },
      {
        "source": "App Store",
        "n": 53
      },
      {
        "source": "Play Store",
        "n": 23
      }
    ],
    "summary": "- **Playlist hijacking** – Users report that playlists they start are abruptly interrupted by unrelated tracks, breaking the intended sequence. [1]  \n- **Undesired regional bias** – The algorithm is pushing large amounts of Russian music to users who never listen to it and actively block it. [2][3]  \n- **Discover Weekly lock‑in** – Listeners feel trapped in a loop of poor recommendations with no way to reset or correct the algorithm’s “endorsement” of bad songs. [4]  \n- **Mis‑attributed or anonymous mixes** – Generated playlists appear under someone else’s name or with no clear attribution, causing confusion about who the algorithm is targeting. [8]  \n- **Cross‑platform inconsistency** – Adding songs on mobile doesn’t reflect on the web version, leading users to distrust the algorithm’s coherence across devices. [6]",
    "quotes": [
      {
        "n": 1,
        "snippet": "Something wrong with the playlists. I start to listen to a playlist and it automatically switches to some random songs rather than sticking to the playlist. It’s like the first song is my playlist’s and after that random songs",
        "source": "App Store",
        "date": "2025-03-31",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "This is still happening(now in release radar as well) and I'm considering to switch to some other problem unless spotify stop pushing russian music, e.g. helping russia achiving their goal to russify us and erase Ukrainian identity",
        "source": "Community Forum",
        "date": "2024-01-05",
        "rating": null,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "I have the same problem. It started about six months ago (maybe even earlier), and now at least 50% of Discover Weekly is Russian music, despite the fact that I have never listened to Russian and actively block it. Nothing helps.",
        "source": "Community Forum",
        "date": "2024-05-22",
        "rating": null,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "Upvoting this, I'm stuck in a perpetual loop of bad music as Discover Weekly just keeps recommending it, so inevitibly it plays and Spotify thinks this is some sort of endorsement. Please let me reset. Please god",
        "source": "Community Forum",
        "date": "2017-02-28",
        "rating": null,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "it has very very small amount of repeats, increase it in free mode although with ads.",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 4,
        "segment": ""
      },
      {
        "n": 6,
        "snippet": "The ai mix is slightly better. the ux still poor. when i add to playlist on mobile it works on web its inconsistent.",
        "source": "Play Store",
        "date": "2026-06-23",
        "rating": 3,
        "segment": ""
      },
      {
        "n": 7,
        "snippet": "my huge problem with this app is the shuffle. It plays random songs that I don't like and I don't even want to listen to. unless if you pay. this app is extremely greedy and I really don't like it. I hope they fix this! NOW",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 2,
        "segment": ""
      },
      {
        "n": 8,
        "snippet": "\"Discover Weekly\" displays someone else's name. Discover weekly shows \"Made for Aradhana\". Idk who that is or the songs in the playlist.\nMy name is David.\n\nAnyone else experience this?",
        "source": "Reddit",
        "date": "2025-05-08",
        "rating": null,
        "segment": ""
      }
    ]
  },
  "Discovery friction": {
    "key": "discovery_friction",
    "label": "Discovery friction",
    "definition": "It's hard to find or surface genuinely new music; discovery takes effort or doesn't happen at all.",
    "count": 568,
    "negPct": 65,
    "sources": [
      {
        "source": "Reddit",
        "n": 384
      },
      {
        "source": "Community Forum",
        "n": 95
      },
      {
        "source": "App Store",
        "n": 77
      },
      {
        "source": "Play Store",
        "n": 12
      }
    ],
    "summary": "- **Algorithmic echo chamber** – Users feel the recommendation engine keeps serving the same type of tracks (e.g., meditation or baby‑time music) and won’t surface genuinely new songs. [4]  \n- **No way to exclude covers** – Listeners want an option to filter out cover versions from Discover Weekly because they dominate the playlist. [5][6]  \n- **Missing regional/genre content** – The catalog feels thin for certain languages or local scenes (e.g., Hindi songs, South African artists), making discovery harder. [2][8]  \n- **Lack of thematic/emotion playlists** – Users want dedicated collections grouped by mood or theme that are easy to find and use. [7]  \n- **Limited discovery controls** – Restrictions like skip limits and forced ads impede users from exploring new tracks freely. [3][2]",
    "quotes": [
      {
        "n": 1,
        "snippet": "Playlist shuffle. Everything is great! But…\nShuffle of songs within a playlist can be better. Most of the times I only get certain songs from my playlist and the other songs play rarely.",
        "source": "App Store",
        "date": "2023-07-26",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "Suggestions.. You should have a few more hindi song... And advertising should be minimal... There should be a option whether a person want premium membership or not at the beginning of the app when just opened...",
        "source": "App Store",
        "date": "2020-01-14",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "Regarding the song playlist. The fact that there’s already a limit given to skips songs and choose 6 songs we can’t listen to songs that we don’t wanna listen who’s gonna wait for the next day",
        "source": "App Store",
        "date": "2023-09-19",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "You listen to one meditation playlist to fall asleep and bam! nothing but baby time sleep music for months and no amount of hitting the remove button seems to help get it back on track with things I like.",
        "source": "Community Forum",
        "date": "2022-02-22",
        "rating": null,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "I also came here searching for a way to exclude covers from Discover Weekly. Would be a nice feature.",
        "source": "Community Forum",
        "date": "2024-02-12",
        "rating": null,
        "segment": ""
      },
      {
        "n": 6,
        "snippet": "Please make it possible to choose not to have covers on Discover Weekly. I'd say close to 75% of the songs were covers. If not more.",
        "source": "Community Forum",
        "date": "2024-10-22",
        "rating": null,
        "segment": ""
      },
      {
        "n": 7,
        "snippet": "I love all music I just wish that there was a better option to get the playlists gathered by theme or emotion on its own for me.",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 8,
        "snippet": "not that helpful to some SA EC n KZN UNDISCOVERED Obscured ARTISTS.",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 4,
        "segment": ""
      }
    ]
  },
  "Over-personalization": {
    "key": "over_personalization",
    "label": "Over-personalization",
    "definition": "Recommendations are too narrow — users feel trapped in a bubble of the already-familiar.",
    "count": 225,
    "negPct": 81,
    "sources": [
      {
        "source": "Reddit",
        "n": 101
      },
      {
        "source": "Community Forum",
        "n": 59
      },
      {
        "source": "App Store",
        "n": 56
      },
      {
        "source": "Play Store",
        "n": 9
      }
    ],
    "summary": "- **Duplicate/Redundant Recommendations** – Users complain that the same track keeps being suggested or added again, even when it already exists in a playlist [1][5][7].  \n- **Algorithmic Echo Chamber** – The recommendation engine repeatedly serves the same familiar or old tracks, preventing discovery of new music [2][8].  \n- **Involuntary Content Bias** – Certain regional or thematic music (e.g., Russian tracks) is pushed onto users despite their preferences [3].  \n- **Undesired Smart‑Shuffle Prompts** – The Smart Shuffle feature appears on every shuffle action and cannot be turned off, forcing unwanted song selections [4].  \n- **Non‑Playlist Songs Injected into Playback** – Tracks that are not part of the user’s chosen playlist appear during listening, breaking the intended listening experience [6][7].",
    "quotes": [
      {
        "n": 1,
        "snippet": "OG. Kindly add a feature that if a song is already added in a playlist then the same song shouldn’t be recommended through enhance in the same playlist or one song can’t be added twice into a playlist.",
        "source": "App Store",
        "date": "2023-05-14",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "You listen to one meditation playlist to fall asleep and bam! nothing but baby time sleep music for months and no amount of hitting the remove button seems to help get it back on track with things I like.",
        "source": "Community Forum",
        "date": "2022-02-22",
        "rating": null,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "This is still happening(now in release radar as well) and I'm considering to switch to some other problem unless spotify stop pushing russian music, e.g. helping russia achiving their goal to russify us and erase Ukrainian identity",
        "source": "Community Forum",
        "date": "2024-01-05",
        "rating": null,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "I have the same problem with this Smart Shuffle sh*t, it's TOTALLY unnecessary! I want a button where i can turn this off and NEVER EVER see this prompt again 😠 Appearing EVERY single time when i press shuffle 😠 GET RID OF IT",
        "source": "Community Forum",
        "date": "2022-05-05",
        "rating": null,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "man let us listen to our playlist in peace stop adding songs",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 2,
        "segment": ""
      },
      {
        "n": 6,
        "snippet": "my huge problem with this app is the shuffle. It plays random songs that I don't like and I don't even want to listen to. unless if you pay. this app is extremely greedy and I really don't like it. I hope they fix this! NOW",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 2,
        "segment": ""
      },
      {
        "n": 7,
        "snippet": "There's songs that are playing that are not in my playlist, fix this issue, if it's not in my playlist, it shouldn't be playing. I don't need to pay for music, you have enough money at this point greedy music company.",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 1,
        "segment": ""
      },
      {
        "n": 8,
        "snippet": "Im looking to get away from their normal algorithm. It keeps sending me the same music. Discover weekly is mainly now just \"what you listened to 2 years ago\"",
        "source": "Reddit",
        "date": "2025-04-21",
        "rating": null,
        "segment": ""
      }
    ]
  },
  "Sameness fatigue": {
    "key": "sameness_fatigue",
    "label": "Sameness fatigue",
    "definition": "The same songs and artists repeat; the rotation feels stale and predictable.",
    "count": 383,
    "negPct": 85,
    "sources": [
      {
        "source": "Reddit",
        "n": 294
      },
      {
        "source": "Community Forum",
        "n": 62
      },
      {
        "source": "Play Store",
        "n": 14
      },
      {
        "source": "App Store",
        "n": 13
      }
    ],
    "summary": "- **Static playlists lacking fresh rotation** – Users want playlists to change more often instead of staying the same week after week [1][2][8].  \n- **Repeated tracks within and across weeks** – Duplicate songs appear in the current list and re‑appear from previous weeks, undermining discovery [2][3].  \n- **Artist/genre over‑representation** – The shuffle or “smart shuffle” keeps playing songs from the same artist or covers, making the listening experience feel one‑dimensional [4][5][6][7].  \n- **Ineffective shuffle algorithm** – The shuffle feature repeatedly selects similar or identical tracks rather than mixing the library [5][6][7].",
    "quotes": [
      {
        "n": 1,
        "snippet": "Good quality of songs. It has almost 80% of songs have the lyrics also that i do listen to and have good quality of songs.\n\nIn overall good\n\nI would like to recommend that make the playlists more dynamic rather than keep it same.",
        "source": "App Store",
        "date": "2026-03-30",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "@ZullyB The playlist is up, and I didn't get any double repeats this week, but there were still a good 10-15 tracks from previous weeks.",
        "source": "Community Forum",
        "date": "2017-05-08",
        "rating": null,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "@ZullyB What's the reasoning behind this not being an issue? I still say that constantly getting duplicates defeats the entire purpose of a discovery service.",
        "source": "Community Forum",
        "date": "2017-05-09",
        "rating": null,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "This would be so nice!! I like one cover song, and now my entire Playlist is cover songs and it's awful!!",
        "source": "Community Forum",
        "date": "2024-10-29",
        "rating": null,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "All good, but with premium the samrt shuffle or shuffle will the similar songs again and again. if I'd from some artist profile. like it repeat same songs every time.",
        "source": "Play Store",
        "date": "2026-06-23",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 6,
        "snippet": "Great experience, it's one of the few apps that are worth my subscription. I am giving 4 stars because you need to improve the shuffling and not play the same songs for me",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 4,
        "segment": ""
      },
      {
        "n": 7,
        "snippet": "Plays all the top hits of every genre.I ask for. but then it plays the same songs. needs a shuffle for free",
        "source": "Play Store",
        "date": "2026-06-23",
        "rating": 4,
        "segment": ""
      },
      {
        "n": 8,
        "snippet": "Discover Weekly giving me the same songs again?.",
        "source": "Reddit",
        "date": "2025-05-05",
        "rating": null,
        "segment": ""
      }
    ]
  },
  "Intent expression gap": {
    "key": "intent_expression_gap",
    "label": "Intent expression gap",
    "definition": "Users can't tell Spotify what they actually want right now — no way to express in-the-moment intent.",
    "count": 199,
    "negPct": 34,
    "sources": [
      {
        "source": "Reddit",
        "n": 136
      },
      {
        "source": "App Store",
        "n": 31
      },
      {
        "source": "Community Forum",
        "n": 28
      },
      {
        "source": "Play Store",
        "n": 4
      }
    ],
    "summary": "- **No way to hide or block unwanted recommendations** – users can’t remove songs they dislike from Discover Weekly or stop specific content (e.g., a podcast) from being suggested again [1][3].  \n- **Inability to preserve playlist order** – listeners are forced into shuffle mode and can’t play a playlist in the exact order they added tracks [5][6].  \n- **Difficulty saving or extracting tracks from algorithmic mixes** – users want an easy way to add songs from Discover Weekly to their library or playlists, but the process is unclear [7][8].  \n- **Ads interrupting the listening experience** – free‑tier users complain that frequent ads break flow and feel pressured to upgrade [6].  \n- **Cross‑platform playlist syncing challenges** – creating playlists on other services (e.g., YouTube) and syncing them to Spotify still leaves gaps in getting the exact songs they want [4].",
    "quotes": [
      {
        "n": 1,
        "snippet": "its been removed, can no longer hide songs i dont like in my discover weekly",
        "source": "Community Forum",
        "date": "2024-11-19",
        "rating": null,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "Check out this Idea below, leave your Kudos and comments there. https://community.spotify.com/t5/Live-Ideas/All-Platforms-Other-quot-Reset-Taste-Profile-History-quo...",
        "source": "Community Forum",
        "date": "2016-06-03",
        "rating": null,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "I would like to block the Joe Rogan podcast from being recommended.",
        "source": "Community Forum",
        "date": "2022-01-17",
        "rating": null,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "i always create my playlists with YouTube and sync them to Spotify. best approach so far. as for getting exactly song's still a challenge.but it's Good. music Vybz awesome.",
        "source": "Play Store",
        "date": "2026-06-21",
        "rating": 5,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "you need premium if u want to listen to a playlist with the songs organized instead of shuffled",
        "source": "Play Store",
        "date": "2026-06-24",
        "rating": 4,
        "segment": ""
      },
      {
        "n": 6,
        "snippet": "STAWP WITH DA ADS PLEASE OMG. we know you want us to buy premium but you don't have to throw ads at us every single second :< . Have mercyy and stop shuffling the playlist play it in the order we add it bruh that would help a lot.",
        "source": "Play Store",
        "date": "2026-06-22",
        "rating": 4,
        "segment": ""
      },
      {
        "n": 7,
        "snippet": "Track songs saved from discover weekly?.",
        "source": "Reddit",
        "date": "2025-04-17",
        "rating": null,
        "segment": ""
      },
      {
        "n": 8,
        "snippet": "Discover Weekly. Out of the 30 songs each week I add between 5 and 10 to my liked songs.",
        "source": "Reddit",
        "date": "2025-04-26",
        "rating": null,
        "segment": ""
      }
    ]
  },
  "Passive discovery failure": {
    "key": "passive_discovery_failure",
    "label": "Passive discovery failure",
    "definition": "The automated surfaces (Discover Weekly, Release Radar, radio) under-deliver on novelty.",
    "count": 148,
    "negPct": 66,
    "sources": [
      {
        "source": "Reddit",
        "n": 97
      },
      {
        "source": "Community Forum",
        "n": 30
      },
      {
        "source": "App Store",
        "n": 19
      },
      {
        "source": "Play Store",
        "n": 2
      }
    ],
    "summary": "- **Playlist‑radio removal** – Users report that the radio station option for playlists (accessed via the three‑dot menu) has vanished, removing a feature they preferred over Discover Weekly. [1][2]  \n- **Release Radar genre loss** – Some users notice that entire sections of Release Radar (e.g., classical music) disappear, leaving the feed less diverse and novel. [3]  \n- **Discover Weekly stagnation or disappearance** – After weeks or months of use, the weekly personalized playlist either fails to update or is completely missing. [5][6][7]  \n- **Local‑track autoplay issues** – When local files are mixed with Spotify’s curated playlists, the playback does not transition smoothly, breaking the discovery flow. [4]",
    "quotes": [
      {
        "n": 1,
        "snippet": "I discovered playlist radio feature just a few days ago, and I was so happy how great it was! And just now I’ve noticed it’s gone. So unfortunate.  Why? Please bring it back. It does much better than Discover weekly and artist/album radio.",
        "source": "Community Forum",
        "date": "2023-03-19",
        "rating": null,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "It seems that when you click on the 3 dots next to a playlist, you can’t go to the radio station of the playlist anymore. I loved that feature, please bring it back!",
        "source": "Community Forum",
        "date": "2023-03-21",
        "rating": null,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "Happened to me as well when checking Release Radar today, last Friday it still had the usual 200 tracks. All classical music is missing now which was a large part of it.",
        "source": "Community Forum",
        "date": "2024-08-06",
        "rating": null,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "Local songs (songs from my device) cannot autoplay play smoothly with the app's songs in any curated playlist. Nevertheless, the app's superb and should be on every song lover's default apps 👍",
        "source": "Play Store",
        "date": "2026-06-23",
        "rating": 4,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "I have no discover weekly after using it for a year?.",
        "source": "Reddit",
        "date": "2025-03-31",
        "rating": null,
        "segment": ""
      },
      {
        "n": 6,
        "snippet": "I have no discover weekly after using the app for nearly a year.",
        "source": "Reddit",
        "date": "2025-03-31",
        "rating": null,
        "segment": ""
      },
      {
        "n": 7,
        "snippet": "Discover Weekly. i look forward to this every week and this week it hasn’t updated yet . has anybody else experienced this ?",
        "source": "Reddit",
        "date": "2025-02-21",
        "rating": null,
        "segment": ""
      }
    ]
  },
  "Profile pollution fear": {
    "key": "profile_pollution_fear",
    "label": "Profile pollution fear",
    "definition": "Users fear one play — or even a skip — will wreck their recommendations and long-term taste profile.",
    "count": 78,
    "negPct": 91,
    "sources": [
      {
        "source": "Reddit",
        "n": 46
      },
      {
        "source": "Community Forum",
        "n": 29
      },
      {
        "source": "App Store",
        "n": 2
      },
      {
        "source": "Play Store",
        "n": 1
      }
    ],
    "summary": "- **Foreign‑language/genre bleed‑through** – Users see large portions of their Discover Weekly filled with music (e.g., Russian tracks) they’ve never listened to and have even blocked. [1]  \n- **Cross‑account contamination** – Listening activity from other people (e.g., a partner) is mistakenly influencing the user’s recommendations, making the feed feel “not me.” [2]  \n- **No easy reset for the algorithm** – Listeners want a way to wipe or restart their recommendation profile after a period of bad data (e.g., network‑driven listening to backup playlists). [3]  \n- **Followed‑artist leakage** – Artists a user follows keep reappearing in Discover Weekly and Release Radar, even when the user prefers they stay out of those mixes. [4][6]  \n- **AI‑generated “fake” artists polluting feeds** – Algorithm‑created or AI‑driven acts show up in Release Radar, confusing users who expect only real artists. [5]",
    "quotes": [
      {
        "n": 1,
        "snippet": "I have the same problem. It started about six months ago (maybe even earlier), and now at least 50% of Discover Weekly is Russian music, despite the fact that I have never listened to Russian and actively block it. Nothing helps.",
        "source": "Community Forum",
        "date": "2024-05-22",
        "rating": null,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "I did that what a while ago, but it's still suggesting songs she would listen to, not me. And yes, I'm certain she's not using it.",
        "source": "Community Forum",
        "date": "2016-02-19",
        "rating": null,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "I wish there was a way to reset the discover weekly. The wifi at my goes down routinely and I had to use my playlist as an emergency backup. Now my once awesome discover weekly has work music popping up all over the place 😞",
        "source": "Community Forum",
        "date": "2016-06-01",
        "rating": null,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "Release radar is based on artists you follow. You might want to curate and unfollow them if they show up on your RR and you don’t like it.",
        "source": "Reddit",
        "date": "2025-03-01",
        "rating": null,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "ai artists using actual artists as stepping stones towards \"success\" have popped up on my release radar 😔.",
        "source": "Reddit",
        "date": "2025-02-23",
        "rating": null,
        "segment": ""
      },
      {
        "n": 6,
        "snippet": "Spotify put my one of my followed artist on discovery weekly and release radars . They can’t keep getting away from this",
        "source": "Reddit",
        "date": "2024-10-28",
        "rating": null,
        "segment": ""
      }
    ]
  },
  "Context / mood mismatch": {
    "key": "context_mood_mismatch",
    "label": "Context / mood mismatch",
    "definition": "Recommendations ignore the user's mood, activity, or listening context.",
    "count": 85,
    "negPct": 81,
    "sources": [
      {
        "source": "Reddit",
        "n": 56
      },
      {
        "source": "App Store",
        "n": 13
      },
      {
        "source": "Community Forum",
        "n": 12
      },
      {
        "source": "Play Store",
        "n": 4
      }
    ],
    "summary": "- **Mood‑Blind Song Selection** – Users report that the app’s “smart choice” or recommendation engine fails to deliver tracks that fit their current emotional state, delivering “bad” mood‑matching songs. [1]  \n- **Context‑Blind Album Playback** – When users are listening to a specific album, Spotify still injects unrelated recommendations, ignoring the immediate listening context. [2]  \n- **Insufficient Granularity for Niche Moods** – Listeners seeking very specific vibes (e.g., “toxic ex” metalcore or a “distorted, fever‑dream summer” feel) receive generic suggestions that don’t capture those nuanced moods. [4][5]  \n- **Ad‑Driven Disruption of Mood Continuity** – Advertisements interrupt the listening flow, breaking the mood and causing the overall experience to feel mismatched. [2]",
    "quotes": [
      {
        "n": 1,
        "snippet": "Stucked always , quality is bad , song choice of smart choice is bad not getting proper mood through songs and suggestions bad",
        "source": "Play Store",
        "date": "2026-06-22",
        "rating": 2,
        "segment": ""
      },
      {
        "n": 2,
        "snippet": "ads and the absolute horrible song recommendations when trying to listen to an album",
        "source": "Play Store",
        "date": "2026-06-23",
        "rating": 1,
        "segment": ""
      },
      {
        "n": 3,
        "snippet": "was browsing through my old photos and I still can't over this. the algorithm was onto something.",
        "source": "Reddit",
        "date": "2025-02-09",
        "rating": null,
        "segment": ""
      },
      {
        "n": 4,
        "snippet": "Toxic ex songs?. Any metalcore recommendations out there???",
        "source": "Reddit",
        "date": "2025-05-04",
        "rating": null,
        "segment": ""
      },
      {
        "n": 5,
        "snippet": "Summer Songs Recommendations. I'm making a Playlist for summertime! I'm looking for songs that sound like summer, but in a distorted, fever dream way! They can be happy, sad, lovey dovey, or anything in between!! Thank you all!",
        "source": "Reddit",
        "date": "2025-04-30",
        "rating": null,
        "segment": ""
      }
    ]
  }
};